apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api
  namespace: autograde
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hitman99/autograde:v0.1
          imagePullPolicy: IfNotPresent
          command:
            - autograde
            - api
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: autograde
                  key: GITHUB_TOKEN
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: autograde
                  key: ADMIN_TOKEN
            - name: CHECK_INTERVAL
              value: "1m"
            - name: REDIS_ADDRESS
              value: "redis:6379"
      imagePullSecrets:
        - name: gitlab-com

---

---

kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: autograde
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80