kind: ConfigMap
metadata:
  name: lab-1
  namespace: autograde
apiVersion: v1
data:
  tasks: |
    - name: checkFork
      kind: github
      config: 
        repo: cloud-lab
      description: github build action checke
      score: 2
    - name: checkBuildAction
      kind: github
      config: 
        repo: cloud-lab
        buildAction: .github/workflows/release.yml
      description: github fork checke
      score: 2
    - name: checkRepo
      kind: dockerhub
      config:
        repo: cloud-lab
      description: dockerhub repository existense check
      score: 1
    - name: checkTags
      kind: dockerhub
      config:
        repo: cloud-lab
      description: dockerhub repository tags check
      score: 1
    - name: checkContainerImage
      kind: kubernetes
      config: 
        imageName: cloud-lab
        deploymentLabelSelector: lab=microservices
      description: kubernetes container image check
      score: 1
    - name: checkEndpointExists
      kind: kubernetes
      config: 
        serviceName: lab
      description: service endpoint check inside kubernetes
      score: 1
    - name: checkEndpointResult
      kind: kubernetes
      config: 
        serviceName: lab
      description: service endpoint result check inside kubernetes
      score: 2