kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: autograde
  namespace: autograde
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - secretName: autograde-tls

  rules:
    - host: b79d2d57-c967-4074-948e-3ad103dccedb.lab.cloudcat.online
      http:
        paths:
          - path: /
            backend:
              serviceName: signup
              servicePort: 80
          - path: /signup
            backend:
              serviceName: signup
              servicePort: 80
          - path: /lab
            backend:
              serviceName: api
              servicePort: 80
          - path: /control
            backend:
              serviceName: signup
              servicePort: 80